import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import mfaRouter from "./mfa";
import signingKeysRouter from "./signingKeys";
import peopleRouter from "./people";
import boardsRouter from "./boards";
import meetingsRouter from "./meetings";
import votesRouter from "./votes";
import minutesRouter from "./minutes";
import documentsRouter from "./documents";
import tasksRouter from "./tasks";
import pendingActionsRouter from "./pendingActions";
import aiRouter from "./ai";
import dashboardRouter from "./dashboard";
import systemRouter from "./system";
import auditLogRouter from "./auditLog";
import deletedRecordsRouter from "./deletedRecords";
import legalHoldsRouter from "./legalHolds";
import accessEventsRouter from "./accessEvents";
import workflowsRouter from "./workflows";
import graphRouter from "./graph";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(mfaRouter);
router.use(signingKeysRouter);
router.use(peopleRouter);
router.use(boardsRouter);
router.use(meetingsRouter);
router.use(votesRouter);
router.use(minutesRouter);
router.use(documentsRouter);
router.use(tasksRouter);
router.use(pendingActionsRouter);
router.use(aiRouter);
router.use(dashboardRouter);
router.use(systemRouter);
router.use(auditLogRouter);
router.use(deletedRecordsRouter);
router.use(legalHoldsRouter);
router.use(accessEventsRouter);
router.use(workflowsRouter);
router.use(graphRouter);

export default router;
