kind = "web"
previewPath = "/"
title = "EasyBoard v2"
version = "1.0.0"
id = "artifacts/easyboard"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25532

[services.development]
run = "pnpm --filter @workspace/easyboard run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/easyboard", "run", "build" ]
publicDir = "artifacts/easyboard/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25532"
BASE_PATH = "/"
